# Production Environment Profile

profile_name: prod
description: Production environment with full usage and high availability
environment: production

# Core Assumptions
assumptions:
  - "Resources run 24/7 with high availability requirements"
  - "Production-level traffic and data transfer"
  - "30-day backup retention for compliance"
  - "Multi-AZ deployment for critical services"
  - "Performance and availability prioritized over cost"

# Default Usage Parameters
defaults:
  # General
  uptime_hours_per_month: 730  # 24/7 (365 days / 12 months * 24 hours)
  uptime_percentage: 100  # Full uptime
  availability_target: 99.9  # percent (three nines)
  
  # EC2 Compute
  ec2_uptime_hours: 730
  ec2_cpu_utilization: 60  # percent
  ec2_memory_utilization: 70  # percent
  ec2_network_out_gb: 500  # GB/month
  ec2_network_in_gb: 250  # GB/month
  ec2_ebs_iops: 1000  # IOPS for gp3
  
  # S3 Storage
  s3_storage_gb: 1000  # GB average (1 TB)
  s3_requests_get: 1000000  # 1M GET requests/month
  s3_requests_put: 100000  # 100K PUT requests/month
  s3_requests_list: 50000  # LIST requests/month
  s3_data_transfer_out_gb: 250  # GB/month
  s3_data_retrieval_gb: 500  # GB/month
  
  # RDS Database
  rds_uptime_hours: 730
  rds_storage_gb: 500  # GB
  rds_backup_storage_gb: 15000  # GB (30x storage for 30-day retention)
  rds_backup_retention_days: 30
  rds_iops: 1000  # Provisioned IOPS
  rds_connections: 200  # Average concurrent connections
  
  # ELB Load Balancer
  elb_uptime_hours: 730
  elb_processed_gb: 500  # GB/month
  elb_connections_per_second: 200  # Average
  elb_new_connections_per_second: 100
  elb_active_connections: 2000
  elb_lcu_hours: 730
  
  # NAT Gateway
  nat_uptime_hours: 730
  nat_processed_gb: 500  # GB/month
  
  # EKS Cluster
  eks_uptime_hours: 730
  eks_worker_nodes: 5
  eks_pods_per_node: 30

# Scaling Factors for Scenarios
scaling:
  min_factor: 0.5  # 50% of expected
  max_factor: 1.5  # 150% of expected
